

src:
  datasource:
    jdbc-url: jdbc:mysql://{serverIP}:{port}/{db}?useUnicode=true&characterEncoding=utf-8&serverTimezone=CST&useServerPrepStmts=true
    username: user
    password: pwd

target:
  datasource:
    jdbc-url: jdbc:mysql://{serverIP}:{port}/{db}?useUnicode=true&characterEncoding=utf-8&serverTimezone=CST&useServerPrepStmts=true
    username: user
    password: pw
server:
  compression:
    enabled: true
    min-response-size: 102400 # 100KB
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json