pages:
  stage: deploy
  image: hub.cloud.ctripcorp.com/devops/centos7.2:0.0.1
  script:
    - mkdir .temp
    - cp -r * .temp
    - mv .temp public
  only:
    refs:
      - master
  artifacts:
    paths:
      - public